
name: robcrawford.github.io
description: Website
author:
  name: Rob Crawford
  email: robcrawford@users.noreply.github.com
kramdown:
  input: GFM

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - README.md
  - run.sh
  - yarn.lock
